### ISSUE TITLE
How to use in Xamarin project?

### ISSUE THREAD

**Issue by mrtnkrstn** [Kawaian/OpenCvSharp#2]
Hi

I have added the NuGet package to a Xamarin.iOS project, get the following error when running the app (builds fine): 

```
System.TypeInitializationException: The type initializer for 'OpenCvSharp.Mat' threw an exception. ---> System.TypeInitializationException: The type initializer for 'OpenCvSharp.NativeMethods' threw an exception. ---> OpenCvSharp.OpenCvSharpException: OpenCvSharpExtern
*** An exception has occurred because of P/Invoke. ***
Please check the following:
(1) OpenCV's DLL files exist in the same directory as the executable file.
(2) Visual C++ Redistributable Package has been installed.
(3) The target platform(x86/x64) of OpenCV's DLL files and OpenCvSharp is the same as your project's.

System.DllNotFoundException: OpenCvSharpExtern
```

Using **Visual Studio for Mac**. Not sure how to fix the above error.

Any help will be greatly appreciated!

**Comment by gmlwns2000** [comment]
Hi @mrtnkrstn ,

Unfortunatly, OpenCvSharp doesn't support iOS at this point..
To support iOS, you should build [OpenCvSharpExtern](https://github.com/Kawaian/OpenCvSharp/tree/master/src/OpenCvSharpExtern) for iOS. Just like a [OpenCvSharpExternDroid](https://github.com/Kawaian/OpenCvSharp/tree/master/src/OpenCvSharpExternDroid).
And then add OpenCvSharp (PCL) and create iOS native bin wrapper library like OpenCvSharp.Android.
And then add them into your Xamarin project.

I hope this may help you ;3

P.S. Btw, I can't build and test iOS libraries cuz, I don't have any mac...

**Comment by James-Aidoo** [comment]
> Hi @mrtnkrstn ,
> 
> Unfortunatly, OpenCvSharp doesn't support iOS at this point..
> To support iOS, you should build [OpenCvSharpExtern](https://github.com/Kawaian/OpenCvSharp/tree/master/src/OpenCvSharpExtern) for iOS. Just like a [OpenCvSharpExternDroid](https://github.com/Kawaian/OpenCvSharp/tree/master/src/OpenCvSharpExternDroid).
> And then add OpenCvSharp (PCL) and create iOS native bin wrapper library like OpenCvSharp.Android.
> And then add them into your Xamarin project.
> 
> I hope this may help you ;3
> 
> P.S. Btw, I can't build and test iOS libraries cuz, I don't have any mac...

Sorry to comment on a closed thread... could you please give some guidelines on how to build it for Xamarin.iOS?
