### ISSUE TITLE
Building OpenCvSharpExtern unable to find project error

### ISSUE THREAD

**Issue by rijesha** [Kawaian/OpenCvSharp#4]
Hi when I open the solution and build openCvSharpExtern I get the build errors that OpenCvSharp.Extensions and OpenCvSharp.Blob project files may be invalid or missing targets required.

I manually added OpenCvSharp.Extensions to the solution and attempted to build.
My first error was "the type or namespace Mat can not be found. are you missing a using directive or an assembly?"

The files do include the using opencvsharp directive so im not sure what the problem is.

**Comment by rijesha** [comment]
The error was with the .net framwork. The .csproj was set to net4.0 but the rest was compiled with net4.6. Im not sure what framework i should be using.

**Comment by gmlwns2000** [comment]
Hi @rijesha 
Hmm... Did you trying to load OpenCvSharp.Tests? It is broken currently. 
You should build OpenCvSharp.Tests.Windows to test this project. Make sure your build platform is Win_x64. x64, x86, ARM, ARM64 is for Android build. And OpenCvSharp.Extensions's classes (bitmap converters etc) is in OpenCvSharp.Windows now.
